# Generated by Django 5.0.7 on 2024-08-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskmodel_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='tasks',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_assign_date',
            field=models.DateTimeField(),
        ),
    ]
